image: python:3.8

pipelines:
  branches:
    develop:
      - step:
          name: Package Artifact
          image: atlassian/default-image:2
          script:
            - zip -r artifact.zip *
          artifacts:
            - artifact.zip

      - step:
          name: Install Dependencies And Deploy
          script:
            - pip install boto3==1.3.0
            - python codedeploy_deploy.py
